In [1]:
import numpy as np

In [2]:
data = np.load('node_features_2015.npy')

In [3]:
data.shape

(365, 77, 8)

In [4]:
start_idx = 7
while True:
    if start_idx > len(data):
        break
    print(data[start_idx, 0, :])
    start_idx = start_idx + 8

[1. 0. 0. 1. 0. 1. 0. 0.]
[1. 2. 0. 2. 1. 2. 0. 3.]
[1. 5. 0. 0. 0. 0. 1. 2.]
[0. 5. 0. 1. 0. 0. 0. 2.]
[2. 1. 0. 2. 0. 1. 0. 1.]
[0. 4. 0. 1. 0. 0. 1. 2.]
[1. 2. 1. 0. 0. 1. 1. 3.]
[1. 3. 0. 0. 1. 0. 1. 2.]
[0. 3. 0. 0. 3. 0. 0. 5.]
[0. 4. 0. 1. 1. 1. 0. 0.]
[1. 3. 0. 3. 0. 0. 0. 1.]
[1. 1. 0. 0. 1. 0. 0. 2.]
[0. 2. 0. 2. 0. 0. 1. 1.]
[2. 2. 0. 0. 1. 0. 1. 1.]
[0. 1. 0. 1. 0. 1. 0. 2.]
[0. 2. 0. 2. 0. 0. 0. 1.]
[0. 0. 0. 2. 1. 1. 0. 1.]
[0. 3. 1. 0. 1. 0. 0. 1.]
[0. 3. 1. 0. 0. 1. 1. 5.]
[0. 0. 1. 1. 1. 0. 0. 2.]
[0. 2. 0. 1. 0. 0. 0. 0.]
[1. 2. 0. 2. 0. 1. 0. 4.]
[0. 3. 0. 3. 1. 2. 1. 2.]
[1. 3. 0. 2. 0. 2. 2. 1.]
[0. 2. 2. 2. 0. 0. 0. 4.]
[0. 4. 1. 3. 1. 0. 0. 3.]
[0. 2. 0. 1. 0. 0. 2. 3.]
[0. 4. 3. 1. 0. 1. 0. 1.]
[2. 0. 0. 1. 2. 0. 0. 3.]
[0. 4. 0. 2. 2. 0. 0. 3.]
[3. 2. 0. 2. 0. 0. 0. 2.]
[0. 2. 1. 1. 2. 0. 0. 3.]
[2. 2. 0. 2. 1. 0. 1. 3.]
[0. 0. 2. 1. 0. 0. 1. 6.]
[0. 1. 2. 1. 0. 0. 1. 1.]
[2. 0. 0. 2. 0. 0. 0. 4.]
[0. 4. 0. 1. 0. 0. 1. 3.]
[0. 0. 1. 2. 0. 0. 0. 2.]
[0. 0. 0. 1.

In [5]:
data[23, 0, :]

array([1., 5., 0., 0., 0., 0., 1., 2.])

In [6]:
adj = np.load('adj_mat.npy')

In [7]:
adj

array([[1.        , 1.        , 0.93043053, ..., 0.        , 0.        ,
        1.        ],
       [1.        , 1.        , 0.96752395, ..., 0.        , 0.        ,
        1.        ],
       [0.93043053, 0.96752395, 1.        , ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [1.        , 1.        , 1.        , ..., 0.        , 0.        ,
        1.        ]])